name: expense_manager
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  sqflite: ^2.3.0
  path: ^1.8.3

  # table
  table_calendar: ^3.0.9

  #date time format
  intl: ^0.18.1
  syncfusion_flutter_charts: ^23.1.43
  pie_chart: ^5.4.0
  shared_preferences: ^2.2.2
  line_icons: ^2.0.3
  google_fonts: ^6.1.0
  firebase_auth: ^6.1.1
  firebase_core: ^4.2.0
  firebase_app_check:
  google_sign_in:
  cloud_firestore:
  get_it: ^8.2.0
  go_router: ^16.3.0
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  connectivity_plus: ^5.0.2
  uuid: ^4.5.2
  fpdart: ^1.1.1
  # carousel_slider: ^4.0.0



dev_dependencies:
  build_runner: ^2.6.0
  go_router_builder: ^4.0.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/

  fonts:
    - family: Roboto Mono
      fonts:
        - asset: fonts/RobotoMono-Bold.ttf
          weight: 700
        - asset: fonts/RobotoMono-Regular.ttf
          weight: 400
        - asset: fonts/RobotoMono-Medium.ttf
          weight: 500




  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
